Repository openshift-online/ocm-cli, pull requests merged in 2025-06, with the labels that each got.

#790 Release v1.0.6
  CHANGES.md
  pkg/info/info.go
Labels: lgtm

#793 OCM-9528 | Expose FIPS flag in OCM CLI when provisioning an OSD cluster on Google Cloud
  cmd/ocm/create/cluster/cmd.go
  pkg/cluster/cluster.go
Labels: lgtm, needs-ok-to-test, approved

#795 OCM-16225 | Cannot set param "--subscription-type", always get error
  cmd/ocm/create/cluster/cmd.go
Labels: lgtm, needs-ok-to-test
